language: python
python:
 - 3.6

env:
  - TOX_ENV=py27
  - TOX_ENV=py36

install:
    pip install tox

script: tox -e $TOX_ENV

# flakes show some unused imports and start imports, so we don't want to have red build till they are fixed
after_script: tox -e flakes
